### ISSUE TITLE
Proposal: Debugging

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#105]
My experience during debugging merging classes - I was mainly using:
- command `wasm-pack test --firefox --headless -- --lib merge_classes`
- alternative to `console.log`: `log!(format!("Something: {:#?}", something))`

I think that there are more user-friendly ways or we can create them. Add your ideas into this issue and we can resolve them in the future.

**Comment by David-OConnor** [comment]
An immediate approach that comes to mind for 2 is to implement a `debug!` macro which wraps the argument in a `{:?}` format. I'm looking into a way to make `log!` accept either, which would be better. I've run into this a number of times as well.

**Comment by David-OConnor** [comment]
Added this, as well as a macro for it (for multiple items, separated by commas) in the latest commit.

**Comment by David-OConnor** [comment]
For #1, we could add something like this to your Makefile:
```TOML
[tasks.test_one]
description = "Run Seed's tests. Ex: 'cargo make test firefox'. Test envs: [chrome, firefox, safari]"
clear = true
workspace = false
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["test", "--firefox", "--headless", "--", "--lib", "${@}"]
```

Note that this only uses firefox.
