### ISSUE TITLE
wasm_bindgen would render twice

### ISSUE THREAD

**Issue by Kilerd** [David-OConnor/seed#195]
the demo in the official site.
we use the code as followed to render wasm:
```js
<section id="app"></section>

<script src="/pkg/package.js"></script>

<script>
  const { render } = wasm_bindgen;
  function run() {
    render();
  }
  wasm_bindgen("/pkg/package_bg.wasm")
    .then(run)
    .catch(console.error);
</script>
```

but the code would render twice component(use the counter demo code).
and I try to render it using this `wasm_bindgen("/pkg/package_bg.wasm");`, it works too.

dependencies version are as followed:
```toml
[dependencies]
seed = "0.4.0"
wasm-bindgen = "0.2.48"
web-sys = "0.3.25"

```

**Comment by David-OConnor** [comment]
Bug

**Comment by MartinKavik** [comment]
> but the code would render twice component(use the counter demo code).

`render` is implicitly called in examples, see https://github.com/David-OConnor/seed/blob/master/examples/counter/src/lib.rs:
```rust
#[wasm_bindgen(start)]   // `start` => call it automatically during initialization
pub fn render() {
    ...
}
```

So we use shorter init script in `index.html`, see https://github.com/David-OConnor/seed/blob/master/examples/counter/index.html:
```html
<script type="module">
  import init from '/pkg/package.js';
  init('/pkg/package_bg.wasm');
</script>
```

**Comment by Kilerd** [comment]
> > but the code would render twice component(use the counter demo code).
> 
> `render` is implicitly called in examples, see https://github.com/David-OConnor/seed/blob/master/examples/counter/src/lib.rs:
> 
> ```rust
> #[wasm_bindgen(start)]   // `start` => call it automatically during initialization
> pub fn render() {
>     ...
> }
> ```
> 
> So we use shorter init script in `index.html`, see https://github.com/David-OConnor/seed/blob/master/examples/counter/index.html:
> 
> ```
> <script type="module">
>   import init from '/pkg/package.js';
>   init('/pkg/package_bg.wasm');
> </script>
> ```
> 
> (I didn't try it, it's my first guess)

it seems that using `import init from '/pkg/package.js'` is not working on seed `0.4.0`.

the brower raise the error saying module does not have the default export

**Comment by MartinKavik** [comment]
I've just pulled `master` and counter example seems working (Firefox, Windows 10).

@Kilerd How do you build your project? Check your `Makefile.toml` or command you are using for building because we changed `wasm-pack`'s `target` from `no-modules` to `web`, e.g:
```toml
description = "Build with wasm-pack"
workspace = false
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package", "--dev"]
``` 
`no-modules` is outdated so it can cause your problem with module. More info here: https://rustwasm.github.io/docs/wasm-bindgen/examples/without-a-bundler.html.

---
Back to main issue:
1. I would try to remove
```js
function run() {
    render();
}
```
from init script in`index.html`.

2. Or remove `start` from `#[wasm_bindgen(start)]`
3. Can you post a link to your project if it's in public repo?
